openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /users/{userId}:
    put:
      summary: Update a user
      operationId: updateUser
      parameters:
        - name : userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: User details that need to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
      responses:
        '200':
          description: "ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        '400':
          description: "invalid id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: "unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '403':
          description: "forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: "not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /events/payments:
    post:
      summary: Ingestie eveniment de plată
      operationId: processPaymentEvent
      requestBody:
        description: Datele evenimentului de plată.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentEventRequest"
      responses:
        '200':
          description: OK
        '400':
          description: Cerere invalidă sau câmpuri lipsă.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: Neautorizat.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /events/notifications:
    post:
      summary: Ingestie eveniment de notificare
      operationId: processNotificationEvent
      requestBody:
        description: Datele evenimentului de notificare.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NotificationEventRequest"
      responses:
        '200':
          description: Evenimentul a fost acceptat pentru procesare asincronă.
        '400':
          description: Cerere invalidă sau câmpuri lipsă.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '401':
          description: Neautorizat.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    UserResponse:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
    UserRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
    PaymentEventRequest:
      type: object
      required:
        - transactionId
        - userId
        - amount
        - paymentMethod
      properties:
        transactionId:
          type: string
        userId:
          type: string
        amount:
          type: integer
          format: int32
        paymentMethod:
          type: string
        robloxDefinition:
          type: string
        robuxAstounder:
          type: string
    NotificationEventRequest:
      type: object
      required:
        - recipient
        - messageBody
        - channelType
      properties:
        recipient:
          type: string
        messageBody:
          type: string
        channelType:
          type: string
        sigmaCounter:
          type: integer
          format: int32
          default: 0
        omegaCounter:
          type: integer
          format: int32
          default: 0
        alphaCounter:
          type: integer
          format: int32
          default: 0
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  
