spring:
  application:
    name: chainsaw
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      uri: mongodb://localhost:27017/test
  liquibase:
    change-log: classpath:db/master.json
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifications-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
